/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 5.6.47 : Database - obedient_dev
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`obedient_dev` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `obedient_dev`;

/*Table structure for table `states` */

DROP TABLE IF EXISTS `states`;

CREATE TABLE `states` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `state` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `states` */

insert  into `states`(`id`,`state`,`created_at`,`updated_at`) values 
(1,'ANDHRA PRADESH',NULL,NULL),
(2,'ASSAM',NULL,NULL),
(3,'ARUNACHAL PRADESH',NULL,NULL),
(4,'BIHAR',NULL,NULL),
(5,'GUJRAT',NULL,NULL),
(6,'HARYANA',NULL,NULL),
(7,'HIMACHAL PRADESH',NULL,NULL),
(8,'JAMMU & KASHMIR',NULL,NULL),
(9,'KARNATAKA',NULL,NULL),
(10,'KERALA',NULL,NULL),
(11,'MADHYA PRADESH',NULL,NULL),
(12,'MAHARASHTRA',NULL,NULL),
(13,'MANIPUR',NULL,NULL),
(14,'MEGHALAYA',NULL,NULL),
(15,'MIZORAM',NULL,NULL),
(16,'NAGALAND',NULL,NULL),
(17,'ORISSA',NULL,NULL),
(18,'PUNJAB',NULL,NULL),
(19,'RAJASTHAN',NULL,NULL),
(20,'SIKKIM',NULL,NULL),
(21,'TAMIL NADU',NULL,NULL),
(22,'TRIPURA',NULL,NULL),
(23,'UTTAR PRADESH',NULL,NULL),
(24,'WEST BENGAL',NULL,NULL),
(25,'DELHI',NULL,NULL),
(26,'GOA',NULL,NULL),
(27,'PONDICHERY',NULL,NULL),
(28,'LAKSHDWEEP',NULL,NULL),
(29,'DAMAN & DIU',NULL,NULL),
(30,'DADRA & NAGAR',NULL,NULL),
(31,'CHANDIGARH',NULL,NULL),
(32,'ANDAMAN & NICOBAR',NULL,NULL),
(33,'UTTARANCHAL',NULL,NULL),
(34,'JHARKHAND',NULL,NULL),
(35,'CHATTISGARH',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
